language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_failure:
  email: 
    recipients:
     - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash drat.sh
env:
  global:
    secure: hGQzqplw/xHcHQ+JTfiG00IVEqsgkGAU8F4zbgZbtlKEALOl9knZThIGDoK0YM9zIdgfV4h+xmUidva6DCa4tIT8duQYiR5bqWaG1QAwXThC7aGcbe6LcV7W78A0fd3ypBB2H5okc+ueRYE0DqIUgnkm+7UD0sMAueRZbO/qkmShU57Rdq8SrormY+K8NwOWg4g0fVZNYued8rZ8sF39wpYPOChL6+HmMLNohpEcq1tHhVszejORSUluOGXUBjiukIRFhexNaXAko3xaPKLWHvD/+7bopgB1V2iUsfczTow01y8mPwXOnrxtmm0PGcMkSFVakZ5sDhpJQat+640OlEg7Ygtv972S5Cg6SQ133tBXBK2fDN+G6JrWj4bR3i1KWMf1DNdoE+WXHSMVfSrW1jRidOFnktYaZfPJRk3zjQV3gN7BxazKpJ9h+mFZvQH8XymOBGVz3P6JSKfEwVqdKYM3XgPxOblLITy0x6MsljjqfZgDAoyrGSHKN+WuW2if3D4pCohzz8OVDGinHJgV2V259Ft2sDQquWMyzHznD186VXqIWH79JozFxvKktHOacnGxJu+g0qDw2dPxMO5xzA93M9sG5XktcIENuSTnpbwtyIKFTEJoyA4rLm67roG89ChJJ+qSafDIoWIX9rNtz4mP7NzLC/GLP5igW347uPk=
